### ISSUE TITLE
今天上線 不能用了耶@@

### ISSUE THREAD

**Issue by gda20456** [knowlet/8Comic-Viewer#1]
8comic閱讀器

**Comment by knowlet** [comment]
8Comic 把他們的網址改了https://github.com/knowlet/8Comic-Viewer/commit/996eab99b2bb639c884dea8ed848b463b570ca1b 已修正。

**Comment by gda20456** [comment]
感謝
2016年2月26日 15:12於 "Albert Hsieh" notifications@github.com寫道：
