### ISSUE TITLE
你好 今天上網看圖片好像都讀取不到了@@

### ISSUE THREAD

**Issue by gda20456** [knowlet/8Comic-Viewer#10]
如題

**Comment by cheaster43** [comment]
應該是 8comic 把圖片的連接方式改為比較相對連結的方式有關…
原本 img src 都是以 http 開頭，如 < img src="http：//img?.8comic.com/?/?/?/001_???.jpg" > ，但在今日(2018/08/07)凌晨時 8comic 改為 https 連接，然後所有的圖片連結都改為 < img src="//img?.8comic.com/?/?/?/001_???.jpg" > ，所以 8Comic-Viewer 的 z (程式第21行) 的 match 判斷回饋的結果會是 null ，因為找不到 [/http:\'\/\/img.*\'\.jpg\'/] 。

目前可以把 regular expression 中的 [http:] 拿掉就可以正常了。

不過應該浮在右下角的導覽功能失去 css 效果應該也是因為 8comic 改為 https 連線的關係，因為瀏覽器安全規則，在 https 的網頁中，js/css 檔案的連結不能 over 到 http ，8Comic-Viewer 在指定 css 檔案的 url 是 http ，然後該連結 redirect 到的 url 也是 http ；若要解決這個問題，可以直接修改 css url 到 redirect url 的 https url。

註：在下不太確定 8comic 把網站改為 https 的時間是不是今日(2018/08/07)凌晨，但相關的問題應該是如上面所述。

**Comment by gda20456** [comment]
沒學過編程看不懂.......
 http 是指說把所有的這個都刪掉就可以了嗎@@?

cheaster43 <notifications@github.com> 於 2018年8月7日 週二 下午12:08寫道：

**Comment by cheaster43** [comment]
目前要用的話，你可以把第21行的 [http:] 給拿掉，應該就行了

**Comment by gda20456** [comment]
謝謝^^

cheaster43 <notifications@github.com> 於 2018年8月7日 週二 下午12:43寫道：

**Comment by cheaster43** [comment]
不會，應急的做法，有幫忙到就好。

期待版大的更新

**Comment by knowlet** [comment]
Fixed in 0225b7b
