### ISSUE TITLE
今天好像又無法使用了@@是又改網址了嗎?

### ISSUE THREAD

**Issue by gda20456** [knowlet/8Comic-Viewer#14]
有辦法自己看改什麼網址然後自己改嗎?

**Comment by knowlet** [comment]
對啊又有新網址
當有新網址的時候就要新增不同的 include 去 match 他

**Comment by gda20456** [comment]
不會用QAQ
每次都要麻煩你有點不好意思

Albert Hsieh <notifications@github.com> 於 2019年4月23日 週二 下午8:41寫道：

**Comment by gda20456** [comment]
只要在指令中新增
// @include      /^http[s]?\:\/\/www.comicbus.cc\/online\/.*$/

www.comicbus.cc  這一段就好了嗎?

鄭悠哉 <k481865481865@gmail.com> 於 2019年4月23日 週二 下午8:53寫道：
