### ISSUE TITLE
不能用了@@

### ISSUE THREAD

**Issue by gda20456** [knowlet/8Comic-Viewer#19]
大大要怎麼改壓?

**Comment by knowlet** [comment]
是自動翻頁的問題還是哪邊的問題呢？

**Comment by gda20456** [comment]
我打開新的回數沒有變成一頁的

Albert Hsieh <notifications@github.com> 於 2020年5月11日 週一 上午11:09寫道：

**Comment by CoderPM2011** [comment]
於 #20 增加最近8comic新增的網址

**Comment by gda20456** [comment]
感謝

PM2011 <notifications@github.com> 於 2020年5月11日 週一 下午9:28寫道：

**Comment by zernbox** [comment]
// @include      /^http[s]?\:\/\/comicbus.live\/online\/(a-)\d+\.html(\?ch=\d+.*)?$/
