### ISSUE TITLE
這幾天新出的圖片無法顯示

### ISSUE THREAD

**Issue by gda20456** [knowlet/8Comic-Viewer#4]
如上,順便問一下
請問可以把閱讀到最後一回時顯示這是最後一回取消嗎 常常一直跳出來
還有拉到下面 會跳到下一回太靈敏有時候會看不到最後一張就跳掉了

**Comment by knowlet** [comment]
你好，我隨機開啟了十本漫畫皆無圖片無法顯示問題，請提供你有問題的漫畫連結謝謝。
另外，自動載入下一話功能容易在圖片還未 loading 完時滑動頁面誤觸，如果真的不想要這個功能可以把腳本當中註解 `Auto load next page` 底下部分的程式碼刪掉。

**Comment by gda20456** [comment]
http://v.comicbus.com/online/insurance-2317.html?ch=539
就這幾天新出的我都無法顯示@@

Albert Hsieh notifications@github.com 於 2016年8月9日 上午8:58 寫道：

**Comment by gda20456** [comment]
我把紀錄都砍掉就可以了  謝謝@@

鄭悠哉 k481865481865@gmail.com 於 2016年8月9日 上午9:15 寫道：
