### ISSUE TITLE
最近有一部份漫畫好像無法讀取

### ISSUE THREAD

**Issue by gda20456** [knowlet/8Comic-Viewer#5]
例如在魔王城說晚安

**Comment by CoderPM2011** [comment]
因為與預設生效的網域不同，現在有新的網域**v.nowcomic.com**，可以在設置中新增自訂includes，將該網域加入，設定如下：
`/^http[s]?\:\/\/v.nowcomic.com\/online\/.*$/`

**Comment by gda20456** [comment]
可以了 感謝

2017-07-26 15:11 GMT+08:00 PM2011 <notifications@github.com>:
