### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by gda20456** [knowlet/8Comic-Viewer#6]
最近的圖片有的開不起來@@
海賊王 空中殺人鬼之類的

**Comment by gda20456** [comment]
看不懂@@

2017-08-18 17:35 GMT+08:00 Albert Hsieh <notifications@github.com>:

**Comment by knowlet** [comment]
@gda20456 應該是修好了，更新到 1.51 版試試

**Comment by gda20456** [comment]
可以了   謝謝

2017年8月19日 07:46，"Albert Hsieh" <notifications@github.com>寫道：
