### ISSUE TITLE
打開背景都是黑的沒有圖片

### ISSUE THREAD

**Issue by gda20456** [knowlet/8Comic-Viewer#8]
如標題@@

**Comment by gda20456** [comment]
可以了感謝不過打開後 圖片雖然有出來可是便很小@@ 我用網頁放大可是圖片沒放大


2017-09-10 10:14 GMT+08:00 Albert Hsieh <notifications@github.com>:

**Comment by knowlet** [comment]
抱歉剛更新檔案的時候漏改一行，新版已修正，麻煩更新 ^_^

**Comment by gda20456** [comment]
感謝您:-D

2017年9月11日 01:56，"Albert Hsieh" <notifications@github.com>寫道：
